name: CI workflow

on:
  push:
  pull_request:

jobs:
  test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      matrix:
        tarantool-version: ["1.10", "2.8"]
      fail-fast: false
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install requirements for community
        run: |
          curl -L https://tarantool.io/installer.sh | sudo VER=${{ matrix.tarantool-version }} bash
          sudo apt install -y tarantool-dev cartridge-cli
          cartridge build
          tarantoolctl rocks install luatest

      # This server starts and listen on 8084 port that is used for tests
      - name: Stop Mono server
        run: sudo kill -9 $(sudo lsof -t -i tcp:8084) || true

      - name: Run tests
        run: .rocks/bin/luatest -v -c

  test_pack:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        tarantool-version: ["2.8"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install requirements
        run: |
          curl -L https://tarantool.io/installer.sh | sudo VER=${{ matrix.tarantool-version }} bash
          sudo apt install -y tarantool-dev cartridge-cli

      - name: Test pack rpm (using fake version)
        run: |
          cartridge pack rpm --version 0.0.1

      - name: Test pack deb (using fake version)
        run: |
          cartridge pack deb --version 0.0.1

  create_release:
    if: contains(github.ref, 'tags/')
    needs: [test, test_pack]
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.set_upload_url.outputs.upload_url }}
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.RELEASE_VERSION }}
          draft: true
      - id: set_upload_url
        run: echo "::set-output name=upload_url::${{ steps.create_release.outputs.upload_url }}"

  publish_assets:
    if: contains(github.ref, 'tags/')
    needs: create_release
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        tarantool-version: ["2.8"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV    

      - name: Install requirements
        run: |
          curl -L https://tarantool.io/installer.sh | sudo VER=${{ matrix.tarantool-version }} bash
          sudo apt install -y tarantool-dev cartridge-cli

      - name: Pack rpm
        run: |
          cartridge pack rpm --version ${{ env.RELEASE_VERSION }}

      - name: Pack deb
        run: |
          cartridge pack deb --version ${{ env.RELEASE_VERSION }}

      - name: Upload deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: rotor_${{ env.RELEASE_VERSION }}-1_all.deb
          asset_name: rotor_${{ env.RELEASE_VERSION }}-1_all.deb
          asset_content_type: application/octet-stream

      - name: Upload rpm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: rotor-${{ env.RELEASE_VERSION }}-1.x86_64.rpm
          asset_name: rotor-${{ env.RELEASE_VERSION }}-1.x86_64.rpm
          asset_content_type: application/octet-stream
