name: Release

on:
  push:
  pull_request:

jobs:
  run-tests-ce:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install requirements
        run: |
          curl -L https://tarantool.io/installer.sh | sudo VER=2.6 bash
          sudo apt install -y tarantool-dev cartridge-cli
          
      - name: Pack rpm
        run: |
          cartridge pack rpm --version 0.0.1

      - name: Pack deb
        run: |
          cartridge pack deb --version 0.0.1

      - name: ls
        run: |
          ls
