name: Release

on:
  push:
  pull_request:

jobs:
  run-tests-ce:
    if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master

      - name: Install requirements for community
        run: |
          curl -L https://tarantool.io/installer.sh | sudo VER=2.6 bash
          sudo apt install -y tarantool-dev cartridge-cli
          
      - name: Install requirements for community
        run: |
          cartridge pack rpm

