name: Run tests

on:
  push:
  pull_request:

jobs:
  run-tests-ce:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' && github.event.pull_request.head.repo.owner.login != 'tarantool'
    strategy:
      matrix:
        tarantool-version: ["1.10", "2.6", "2.7"]
      fail-fast: false
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install requirements for community
        run: |
          curl -L https://tarantool.io/installer.sh | sudo VER=${{ matrix.tarantool-version }} bash
          sudo apt install -y tarantool-dev cartridge-cli
          cartridge build
          tarantoolctl rocks install luatest

      # This server starts and listen on 8084 port that is used for tests
      - name: Stop Mono server
        run: sudo kill -9 $(sudo lsof -t -i tcp:8084) || true

      - name: Run tests
        run: .rocks/bin/luatest -v -c
